name = "gloom"
version = "0.1.0"
description = "A hardcore language for buildling extreme systems"

licences = ["Apache-2.0"]
repository = { type = "github", user = "gloom-lang", repo = "gloom" }
links = [{ title = "Website", href = "https://gloom.run" }]

[dependencies]
gleam_stdlib = "~> 0.29"

[dev-dependencies]
gleeunit = "~> 0.10"
